# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 09:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsevent',
            name='image',
            field=models.ImageField(default=datetime.datetime(2017, 5, 4, 9, 45, 10, 123845, tzinfo=utc), upload_to='app/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
